resource_group_name = "vam-rg-new1"
location            = "West US 2"
app_service_plan_name = "dev-plan"
web_app_name        = "dev-web-app"
sku_size            = "B1"
os_type             = "Windows"
